---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: "Fetch your Kubeconfig using `kubectl get secret -n <your-custom-namespace> vcluster-kubeconfig -o jsonpath='{.data.config}' | base64 -d > CONFIG`"
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'entity-id=${{values.name}}'
    backstage.io/kubernetes-namespace: default
    argocd/app-name: ${{values.name | dump}}
  links:
    - url: https://gitea.cnoe.localtest.me:8443/giteaAdmin/${{ values.name }}
      title: Repo URL
      icon: github
spec:
  owner: guests
  lifecycle: experimental
  type: service
  system: ${{values.name | dump}}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{values.name | dump}}
  description: An example system for demonstration purposes
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: guests
  lifecycle: experimental
  type: service
