---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  namespace: default
spec:
  memberOf: [guests]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  namespace: default
spec:
  type: default
  children: []
