---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-store
  namespace: gitea
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-store
  namespace: gitea
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-store
  namespace: gitea
subjects:
  - kind: ServiceAccount
    name: eso-store
    namespace: gitea
roleRef:
  kind: Role
  name: eso-store
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gitea-secret-store
spec:
  provider:
    kubernetes:
      remoteNamespace: gitea
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: gitea
          key: ca.crt
      auth:
        serviceAccount:
          name: eso-store
          namespace: gitea
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-credentials
  namespace: backstage
spec:
  secretStoreRef:
    name: gitea-secret-store
    kind: ClusterSecretStore
  refreshInterval: "0"
  target:
    name: gitea-credentials
  data:
    - secretKey: GITEA_USERNAME
      remoteRef:
        key: gitea-credential
        property: username
    - secretKey: GITEA_PASSWORD
      remoteRef:
        key: gitea-credential
        property: password
